//Song playlist objects
export const allSongs = [
    {
      songId: 1,
      image: `adele.jpeg`,
      name: `Love Is A Game`,
      artist: `Adele`,
      length: 378,
      audio: `love-is-a-game.mp3`,
      playing: false,
    }, {
        songId: 2,
        image: `soho-2.jpeg`,
        name: `You're My World (Soho)`,
        artist: `Anya Taylor-Joy`,
        length: 130,
        audio: `you-are-my-world-soho.mp3`,
        playing: false,
      }, {
        songId: 3,
        image: `everybodys-gotta-live.jpeg`,
        name: `Everybody's Gotta Live`,
        artist: `Love`,
        length: 195,
        audio: `everybodys-gotta-live.mp3`,
        playing: false,
      }, {
        songId: 4,
        image: `warning.jpg`,
        name: `Misery`,
        artist: `Green Day`,
        length: 303,
        audio: `misery.mp3`,
        playing: false,
      }, {
        songId: 5,
        image: `soho-3.jpg`,
        name: `Downtown (Uptempo)`,
        artist: `Anya Taylor-Joy`,
        length: 198,
        audio: `downtown-uptempo.mp3`,
        playing: false,
      }, {
        songId: 6,
        image: `land-of-1000-dances.jpg`,
        name: `Land Of 1000 Dances`,
        artist: `The Walker Brothers`,
        length: 141,
        audio: `land-of-1000-dances.mp3`,
        playing: false,
      }, {
        songId: 7,
        image: `soho-3.jpg`,
        name: `You're My World`,
        artist: `Anya Taylor-Joy`,
        length: 181,
        audio: `you-are-my-world-regular.mp3`,
        playing: false,
      }, {
        songId: 8,
        image: `heroes.jpg`,
        name: `Heroes`,
        artist: `David Bowie`,
        length: 201,
        audio: `heroes.mp3`,
        playing: false,
    }, {
        songId: 9,
        image: `soho-2.jpeg`,
        name: `Neon`,
        artist: `Stephen Price`,
        length: 305,
        audio: `neon.mp3`,
        playing: false,
    }, {
        songId: 10,
        image: `soho-3.jpg`,
        name: `Downtown (Downtempo)`,
        artist: `Anya Taylor-Joy`,
        length: 321,
        audio: `downtown-downtempo.mp3`,
        playing: false,
    } 
]